using System;
using System.ComponentModel;
using Forestry.Eapc.External.Web.Configuration;

namespace Forestry.Eapc.External.Web.Models.Application
{
    /// <summary>
    ///     Root model class containing various sections that can be found in a phytosanitary certificate application.
    /// </summary>
    public class Application
    {
        /// <summary>
        /// This is the internal identifier of the application as generated by the repository (DataVerse0
        /// which normally would be a unique Guid
        /// </summary>
        public string? Identifier { get; set; }

        /// <summary>
        /// This is the unique business identifier of the application in the form defined by the business.
        /// </summary>
        /// <remarks>
        /// This has been created as separate to the <see cref="Identifier"/> because the business identifier format defined
        /// does not play nicely with URL routing.
        /// </remarks>
        [DisplayName("Reference")]
        public string? ReferenceIdentifier { get; set; }
        
        [DisplayName("Date Created")]
        public DateTime? CreationDate { get; set; }

        [DisplayName("Status")]
        public ApplicationState State { get; set; } = ApplicationState.Draft;

        public Section1 Section1 { get; set; } = new();

        public Section2 Section2 { get; set; } = new();

        public Section3 Section3 { get; set; } = new();

        public Section4 Section4 { get; set; } = new();

        public Section5 Section5 { get; set; } = new();

        public Section6 Section6 { get; set; } = new();

        public Section7 Section7 { get; set; } = new();
        
        public Applicant Applicant { get; set; } = new();

        public SupportingDocumentsSection SupportingDocumentsSection { get; set; } = new();

        public Confirmation Confirmation { get; set; } = new();
    }
}